import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SessionProvider from "./providers/SessionProvider";
import CustomCursor from "@/components/CustomCursor";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AIC Recruitment Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  flex flex-col cursor-none min-h-screen  antialiased`}
      >
        <SessionProvider>
          <CustomCursor />
          <Navbar />
          <main className="flex-grow flex flex-col">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
